# Generated by Django 6.0.6 on 2026-07-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagen_url', models.URLField(blank=True, default='', max_length=500)),
                ('categoria', models.CharField(choices=[('extras', 'Extras / Platos'), ('guarniciones', 'Guarniciones'), ('sandwiches', 'Sándwiches'), ('salchipapas', 'Salchipapas'), ('bebidas', 'Bebidas'), ('bebidas_calientes', 'Bebidas Calientes'), ('jugos', 'Jugos Naturales'), ('cocteles', 'Cócteles'), ('postres', 'Postres'), ('frapps', 'Frapps')], default='extras', max_length=30)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ConsumoRestaurante',
        ),
    ]
