# Generated by Django 6.0.6 on 2026-07-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_plato_delete_consumorestaurante'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='imagen_bano',
            field=models.CharField(blank=True, help_text='Foto del cuarto de baño', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='imagen_cama',
            field=models.CharField(blank=True, help_text='Foto detallada de la cama', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='imagen_extra',
            field=models.CharField(blank=True, help_text='Detalles adicionales (jacuzzi, sauna o decoración)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='imagen_principal',
            field=models.CharField(blank=True, help_text='Vista general de la habitación', max_length=500, null=True),
        ),
    ]
