# Generated by Django 6.0.6 on 2026-07-21 10:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_camara'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSauna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pagador', models.CharField(max_length=150)),
                ('dni_pagador', models.CharField(max_length=15)),
                ('cant_adultos', models.PositiveIntegerField(default=1)),
                ('cant_ninos', models.PositiveIntegerField(default=0)),
                ('total_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
