# Generated by Django 6.0.6 on 2026-06-27 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_wellness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_plato', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField(default=1)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_restaurante', to='gestion_wellness.reserva')),
            ],
        ),
    ]
