# Generated by Django 6.0.6 on 2026-06-27 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_wellness', '0002_consumorestaurante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumorestaurante',
            name='reserva',
        ),
        migrations.AddField(
            model_name='consumorestaurante',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consumos_restaurante', to='gestion_wellness.cliente'),
            preserve_default=False,
        ),
    ]
